// <auto-generated />
using System;
using Dwragge.RCloneClient.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dwragge.RCloneClient.Persistence.Migrations
{
    [DbContext(typeof(JobContext))]
    [Migration("20180624113547_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Dwragge.RCloneClient.Persistence.BackupFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Path")
                        .IsRequired();

                    b.Property<bool>("RealTimeUpdates");

                    b.Property<TimeSpan>("SyncTimeSpan");

                    b.HasKey("Id");

                    b.ToTable("BackupFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
