//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dwragge.RCloneClient.CLI.Connected_Services.RCloneManagementServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RCloneManagementServiceClient.IRCloneManagementService")]
    public interface IRCloneManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRCloneManagementService/HelloWorld", ReplyAction="http://tempuri.org/IRCloneManagementService/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRCloneManagementService/HelloWorld", ReplyAction="http://tempuri.org/IRCloneManagementService/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRCloneManagementService/PostHelloJob", ReplyAction="http://tempuri.org/IRCloneManagementService/PostHelloJobResponse")]
        void PostHelloJob(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRCloneManagementService/PostHelloJob", ReplyAction="http://tempuri.org/IRCloneManagementService/PostHelloJobResponse")]
        System.Threading.Tasks.Task PostHelloJobAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRCloneManagementServiceChannel : IRCloneManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RCloneManagementServiceClient : System.ServiceModel.ClientBase<IRCloneManagementService>, IRCloneManagementService {
        
        public RCloneManagementServiceClient() {
        }
        
        public RCloneManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RCloneManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RCloneManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RCloneManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public void PostHelloJob(string name) {
            base.Channel.PostHelloJob(name);
        }
        
        public System.Threading.Tasks.Task PostHelloJobAsync(string name) {
            return base.Channel.PostHelloJobAsync(name);
        }
    }
}
